### PR TITLE
I am committing this project as have added one testcase regarding

### PR DESCRIPTION
**Pull request by pguptey**
cartpage

### CODE REVIEW

**Comment by pgupteqa** [comment]
Hi pgupte,

Please add search page object and some comments in the test class

**Comment by pguptey** [comment]
Hi pglead,

I have added the cart page and comments please verify and check

**Review by pgupteqa — APPROVED** [review]
Hi pguptey,

Reviewed the changes please merge to main branch

**Comment by pguptey** [comment]
Hi pglead,

I have merged the following code to master branch

**Pull request merged**
